villain1 = [
        {'id': 1, 'name': 'Giant Orc', 'ATK': 2200, 'img': 'global/img/giantorc.webp', 'drawn': False},
        {'id': 2, 'name': 'Giant Orc', 'ATK': 2200, 'img': 'global/img/giantorc.webp', 'drawn': False},
        {'id': 3, 'name': 'Giant Orc', 'ATK': 2200, 'img': 'global/img/giantorc.webp', 'drawn': False},
        {'id': 4, 'name': 'Goblin Attack Froce', 'ATK': 2300, 'img': 'global/img/goblin.webp', 'drawn': False},
        {'id': 5, 'name': 'Goblin Attack Froce', 'ATK': 2300, 'img': 'global/img/goblin.webp', 'drawn': False},
        {'id': 6, 'name': 'Goblin Attack Froce', 'ATK': 2300, 'img': 'global/img/goblin.webp', 'drawn': False},
        {'id': 7, 'name': 'Power Pro Lady Sisters', 'ATK': 1950, 'img': 'global/img/powerpro.webp', 'drawn': False},
        {'id': 8, 'name': 'Power Pro Lady Sisters', 'ATK': 1950, 'img': 'global/img/powerpro.webp', 'drawn': False},
        {'id': 9, 'name': 'Neck Hunter', 'ATK': 1750, 'img': 'global/img/neckhunter.webp', 'drawn': False},
        {'id': 10, 'name': 'Neck Hunter', 'ATK': 1750, 'img': 'global/img/neckhunter.webp', 'drawn': False},
        {'id': 11, 'name': 'Neck Hunter', 'ATK': 1750, 'img': 'global/img/neckhunter.webp', 'drawn': False},
        {'id': 12, 'name': 'Perfect Machine King', 'ATK': 2750, 'img': 'global/img/machineking.webp', 'drawn': False},
        {'id': 13, 'name': 'Giant Turtle Who Feeds on Flames', 'ATK': 1400, 'img': 'global/img/gianturtle.webp', 'drawn': False},
        {'id': 14, 'name': 'Giant Turtle Who Feeds on Flames', 'ATK': 1400, 'img': 'global/img/gianturtle.webp', 'drawn': False},
        {'id': 15, 'name': 'Dark Fire Soldier #2', 'ATK': 1700, 'img': 'global/img/darkfire.webp', 'drawn': False},
        {'id': 16, 'name': 'Dark Fire Soldier #2', 'ATK': 1700, 'img': 'global/img/darkfire.webp', 'drawn': False},
        {'id': 17, 'name': 'Dark Fire Soldier #2', 'ATK': 1700, 'img': 'global/img/darkfire.webp', 'drawn': False},
        {'id': 18, 'name': 'Anteatereatingant', 'ATK': 2000, 'img': 'global/img/antea.webp', 'drawn': False},
        {'id': 19, 'name': 'Anteatereatingant', 'ATK': 2000, 'img': 'global/img/antea.webp', 'drawn': False},
        {'id': 20, 'name': 'Perfect Machine King', 'ATK': 2750, 'img': 'global/img/machineking.webp', 'drawn': False},
    ]
