# Generated by Django 4.2.8 on 2024-01-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
    ]
