# Generated by Django 4.2.8 on 2024-01-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_delete_card_player_energy_point_player_heart_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='heart_point',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Yuji', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
