# Generated by Django 4.2.8 on 2024-01-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_remove_player_heart_point_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='heart_point',
            field=models.IntegerField(default=3),
        ),
    ]
