# Generated by Django 4.2.8 on 2024-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_player_villain_strike_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='carta_atual',
            field=models.CharField(default='', max_length=255),
        ),
    ]
