# Generated by Django 4.2.8 on 2024-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_player_carta_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='atk_atual',
            field=models.CharField(default='', max_length=255),
        ),
    ]
