# Generated by Django 4.2.8 on 2024-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_player_atk_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='atk_do_vilao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='carta_do_vilao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
