# Generated by Django 4.2.8 on 2024-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_alter_player_atk_atual_alter_player_atk_do_vilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='atributo_atual',
            field=models.CharField(default='', max_length=255),
        ),
    ]
