# Generated by Django 4.2.8 on 2024-01-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_player_atributo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='life_round2',
            field=models.IntegerField(default=0),
        ),
    ]
