# Generated by Django 4.2.8 on 2024-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_player_life_round2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enemy_life_round2',
            field=models.IntegerField(default=6000),
        ),
    ]
