# Generated by Django 4.2.8 on 2024-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_player_enemy_life_round2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='enemy_life_round2',
            field=models.IntegerField(default=2000),
        ),
    ]
