# Generated by Django 4.2.8 on 2024-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_player_acceleration_player_angel_wing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dark_energy',
            field=models.IntegerField(default=100),
        ),
    ]
