# Generated by Django 4.2.8 on 2024-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_player_dark_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turno',
            field=models.IntegerField(default=0),
        ),
    ]
