# Generated by Django 4.2.8 on 2024-01-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_player_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stand_by',
            field=models.BooleanField(default=False),
        ),
    ]
