# Generated by Django 4.2.8 on 2024-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_player_contagem_player_stand_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='limite',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='dark_energy',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='enemy_life_round2',
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='player',
            name='energy_point',
            field=models.IntegerField(default=200),
        ),
    ]
