# Generated by Django 4.2.8 on 2024-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_player_limite_alter_player_dark_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defesa_acumulada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defesa_acumulada_inimigo',
            field=models.IntegerField(default=0),
        ),
    ]
