# Generated by Django 4.2.8 on 2024-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_player_defesa_acumulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='boss_escolhido',
            field=models.CharField(default='', max_length=255),
        ),
    ]
