# Generated by Django 4.2.8 on 2024-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_player_boss_escolhido'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='boss_escolhido_atk',
            field=models.IntegerField(default=0),
        ),
    ]
