# Generated by Django 4.2.8 on 2024-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_player_poder_somado'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contador_batalha3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='vida_sobrando',
            field=models.IntegerField(default=1),
        ),
    ]
