# Generated by Django 4.2.8 on 2024-02-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_player_contador_batalha3_player_vida_sobrando'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fim',
            field=models.BooleanField(default=False),
        ),
    ]
