# Generated by Django 4.2.8 on 2024-02-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_player_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='resultado',
            field=models.CharField(default='l', max_length=255),
        ),
    ]
