# Generated by Django 4.2.8 on 2024-03-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_player_historiavariavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='historiaVariavel2',
            field=models.IntegerField(default=1),
        ),
    ]
