# Generated by Django 4.2.8 on 2024-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_player_historiavariavel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fase_atual',
            field=models.IntegerField(default=1),
        ),
    ]
