# Generated by Django 4.2.8 on 2024-03-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0038_player_energy_pointfase1_player_life_round2savepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='controle1',
            field=models.IntegerField(default=0),
        ),
    ]
