# Generated by Django 4.2.8 on 2024-03-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0040_player_batalha_em_andamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rising_enerny',
            new_name='rising_energy',
        ),
    ]
