# Generated by Django 4.2.8 on 2024-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0041_rename_rising_enerny_player_rising_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='drawperformed',
            field=models.FloatField(default=False),
        ),
    ]
