# Generated by Django 4.2.8 on 2024-03-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0042_player_drawperformed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batalhar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='comecou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='superou',
            field=models.IntegerField(default=0),
        ),
    ]
