# Generated by Django 4.2.8 on 2024-03-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0043_player_batalhar_player_comecou_player_flip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='venceu_fase2',
            field=models.BooleanField(default=False),
        ),
    ]
